### ISSUE TITLE
FSMField cannot be deferred

### ISSUE THREAD

**Issue by dmytrokyrychuk** [viewflow/django-fsm#186] opened 2017-08-04 14:00 UTC
Consider the model below:

```python
class Article(models.Model):
    author_name = models.CharField(max_length=73)
    state = FSMField(default='draft')
```

After querying this model via `Article.objects.defer('state')...` or `Article.objects.only('author_name')...`, accessing the `state` field will raise `KeyError` around here: https://github.com/kmmbvnr/django-fsm/blob/5293035481b1066c510a38b59ce307ff29693ec8/django_fsm/__init__.py#L266

Normally accessing a deferred field in Django leads to an SQL query to be performed to fetch that one field value and set it on the model.

In `FileField` they overcome this issue by refreshing the field when necessary: https://github.com/django/django/blob/7724879b524711d61b7491a4a9c104d9cff2e1e3/django/db/models/fields/files.py#L166-L170

Since refreshing doesn't work on protected FSMFields, I am not sure if there is a way to fix this for all use cases.

Related issues: #174, #89

**Comment by JannKleen** [comment] 2020-11-26 19:22
I'm experiencing the same issue when deferring other fields. Extending the above example:

```
class Article(models.Model):
    author_name = models.CharField(max_length=73)
    large_content = models.TextField()
    state = FSMField(default='draft')
```

Running this works:

```
>>> Article.objects.first().large_content
""
```

But this raises an error:

```
>>> Article.objects.defer('large_content').first().large_content
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query_utils.py", line 149, in __get__
    instance.refresh_from_db(fields=[field_name])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 635, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 71, in __iter__
    obj = model_cls.from_db(db, init_list, row[model_fields_start:model_fields_end])
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 513, in from_db
    new = cls(*values)
  File "/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py", line 449, in __init__
    self._update_initial_state()
  File "/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py", line 489, in _update_initial_state
    self.__initial_states = dict(
  File "/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py", line 490, in <genexpr>
    (field.attname, field.value_from_object(self)) for field in self.state_fields
  File "/usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py", line 933, in value_from_object
    return getattr(obj, self.attname)
  File "/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py", line 231, in __get__
    return self.field.get_state(instance)
  File "/usr/local/lib/python3.8/site-packages/django_fsm/__init__.py", line 271, in get_state
    return instance.__dict__[self.name]
KeyError: 'status'
```

**Comment by dmytrokyrychuk** [comment] 2020-11-29 19:04
@JannKleen there must be something missing in your extended example because I cannot reproduce the error when accessing other deferred fields. I've just created this repo with the complete project set up to reproduce this issue. Can you take a look here and let me know if I am doing something different from you that is causing this test to pass unexpectedly for me: https://github.com/dmytrokyrychuk/django-fsm-deferred-reproduction/blob/85526a2a4d882a93cc9fd22e5682723887e4467e/newspaper/tests.py#L14

**Comment by JannKleen** [comment] 2020-11-30 17:31
First of all, thank you for putting in the effort of reproducing it in a separate project. I also can't get your setup to fail.
The code in our project is a bit more complicates and the `.defer()` call is on the Manager, however I still can't reproduce this on your project, however in our code, this is fixed by removing the `.defer()` call.

I'll keep trying to reproduce it and will update the issue once I figured out what the cause is.

**Comment by dmytrokyrychuk** [comment] 2020-11-30 22:47
No problem! If you would rather keep the .defer(), take a look at #248. I
made an attempt to fix this issue there. Maybe it will be useful for you.

пн, 30 лист. 2020, 19:31 користувач Jann Kleen <notifications@github.com>
пише:

**Comment by JannKleen** [comment] 2020-12-01 08:39
Awesome, thank you! I just tested it and it solved our issue as well (wherever it was in the end).

**Closed** 2020-12-09 13:02 UTC
Labels: feature
