### ISSUE TITLE
`Model.refresh_from_db` doesn't work with protected option

### ISSUE THREAD

**Issue by Nnonexistent** [viewflow/django-fsm#174] opened 2017-05-19 14:08 UTC
If there is `FSMField` field with `protected=True` in django model then `refresh_from_db` method will fail with AttributeError exception.

```
class ProtectedAccessModel(models.Model):
    status = FSMField(default='new', protected=True)

instance = ProtectedAccessModel()
instance.save()
instance.refresh_from_db()  # <-- AttributeError will be raised
```

**Comment by Nnonexistent** [comment] 2017-05-19 14:16
For my point of view this is a major issue. `refresh_from_db` used widely and supposed to work in any cases.

**Comment by karyon** [comment] 2017-06-06 11:08
duplicate of #89 and documented in #91, although i would definitely appreciate the fix you provide in your PR.

**Comment by kmmbvnr** [comment] 2017-06-08 09:50
As you can see the solution fastly became too complicated.

**Comment by moseb** [comment] 2019-12-06 11:41
This is my current overridden `refresh_from_db` that I use for a workaround. This is for a model that has a single django-fsm field named `status`:

```python
    def refresh_from_db(self, using=None, fields=None):
        """
        Reload instance from database
        but avoid writing to self.status, directly.
        """
        if fields is None:
            refresh_status = True
            fields = [f.name for f in self._meta.concrete_fields]
        else:
            refresh_status = 'status' in fields

        fields_without_status = [f for f in fields if f != 'status']

        with transaction.atomic():
            super().refresh_from_db(using=using, fields=fields_without_status)

            if refresh_status:
                fresh_status = type(self).objects.only('status').get(pk=self.pk).status
                self._meta.get_field('status').set_state(self, fresh_status)
```

**Comment by kmmbvnr** [comment] 2023-12-21 08:54
Since all possible solutions are hacky and thread/async unsafe this one of the reason why the alternative fsm implementation was created

https://docs.viewflow.io/fsm/index.html

**Closed by kmmbvnr** 2023-12-21 08:54 UTC
Labels: feature, postponed
